# Generated by Django 5.1.7 on 2025-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductDescription', models.TextField()),
                ('ProductPrice', models.FloatField()),
                ('StockCount', models.IntegerField(verbose_name=10)),
                ('onSale', models.BooleanField(default=False)),
            ],
        ),
    ]
