# Generated by Django 5.1.7 on 2025-03-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsModel',
        ),
    ]
